--1. What is the total revenue generated by male vs female customers?
select gender, SUM(amount_spent) as revenue
from customer_purchase_pattern
group by gender;


--2. Which customers used a discount but still spent more than the average  amount spent? 
SELECT customer_id,
       amount_spent
FROM customer_purchase_pattern
WHERE discount_used = 'Yes'
  AND amount_spent >= (
      SELECT AVG(amount_spent)
      FROM customer_purchase_pattern
  );

--3. Which are the top 5 products with the highest average rating scores?
select purchased_items, round(avg(rating_score::numeric),2) as "Average Product Rating"
from customer_purchase_pattern
group by purchased_items
order by avg(rating_score) desc
limit 5;

--4. Segment customers into New, Returning and Active based on their total 
-- number of previous purchases, and show the count of each segment.
WITH customer_method AS (
    SELECT customer_id, 
           previous_purchases,
           CASE 
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 15 THEN 'Returning'
               ELSE 'Active'
           END AS customer_segment
    FROM customer_purchase_pattern
)
SELECT customer_segment, 
       COUNT(*) AS "Number of Customers"
FROM customer_method
GROUP BY customer_segment;


--5. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           purchased_items,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS ranked_item
    FROM customer_purchase_pattern
    GROUP BY category, purchased_items
)
SELECT ranked_item,
       category, 
       purchased_items, 
       total_orders
FROM item_counts
WHERE ranked_item <= 3;


-- 6. Are repeat buyers (more than 5 previous purchases) likely to have a membership?
SELECT membership_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_purchase_pattern
WHERE previous_purchases > 5
GROUP BY membership_status;

-- 7.  What is the revenue contribution of each age bracket?
SELECT 
    age_bracket,
    SUM(amount_spent) AS total_revenue
FROM customer_purchase_pattern
GROUP BY age_bracket
ORDER BY total_revenue DESC;

--8. Which 5 products have the highest percentage of purchases with discounts used?
SELECT purchased_items,
       ROUND(100.0 * SUM(CASE WHEN discount_used = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_purchase_pattern
GROUP BY purchased_items
ORDER BY discount_rate DESC
LIMIT 5;

--9.Do membership customers spend more? Compare average spend and total revenue 
--between memeberships and non-members.
SELECT membership_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(amount_spent),2) AS avg_spend,
       ROUND(SUM(amount_spent),2) AS total_revenue
FROM customer_purchase_pattern
GROUP BY membership_status
ORDER BY total_revenue,avg_spend DESC;